export const SERVICES = [
  {
    id: 'netflix',
    name: 'Netflix',
    slug: 'how-to-cancel-netflix',
    cancelUrl: 'https://www.netflix.com/cancelplan',
    category: 'streaming',
    price: '$15.49/mo',
    difficulty: 'easy',
    keywords: ['how to cancel netflix', 'cancel netflix subscription', 'netflix cancellation'],
    related: ['hulu', 'disney-plus', 'max', 'paramount-plus'],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    slug: 'how-to-cancel-spotify',
    cancelUrl: 'https://www.spotify.com/account/subscription/',
    category: 'streaming',
    price: '$11.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel spotify', 'cancel spotify premium', 'spotify subscription cancel'],
    related: ['apple-music', 'youtube-premium', 'amazon-prime'],
  },
  {
    id: 'hulu',
    name: 'Hulu',
    slug: 'how-to-cancel-hulu',
    cancelUrl: 'https://secure.hulu.com/account',
    category: 'streaming',
    price: '$17.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel hulu', 'cancel hulu subscription', 'hulu cancellation'],
    related: ['netflix', 'disney-plus', 'max', 'peacock'],
  },
  {
    id: 'disney-plus',
    name: 'Disney+',
    slug: 'how-to-cancel-disney-plus',
    cancelUrl: 'https://www.disneyplus.com/account/subscription',
    category: 'streaming',
    price: '$13.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel disney plus', 'cancel disney+ subscription', 'disney plus cancellation'],
    related: ['netflix', 'hulu', 'max', 'paramount-plus'],
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    slug: 'how-to-cancel-apple-music',
    cancelUrl: 'https://support.apple.com/en-us/HT202039',
    category: 'streaming',
    price: '$10.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel apple music', 'cancel apple music subscription', 'apple music cancellation'],
    related: ['spotify', 'youtube-premium', 'apple-tv-plus'],
  },
  {
    id: 'apple-tv-plus',
    name: 'Apple TV+',
    slug: 'how-to-cancel-apple-tv-plus',
    cancelUrl: 'https://support.apple.com/en-us/HT202039',
    category: 'streaming',
    price: '$9.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel apple tv plus', 'cancel apple tv+ subscription'],
    related: ['netflix', 'disney-plus', 'apple-music', 'max'],
  },
  {
    id: 'youtube-premium',
    name: 'YouTube Premium',
    slug: 'how-to-cancel-youtube-premium',
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    category: 'streaming',
    price: 'varies',
    difficulty: 'easy',
    keywords: ['how to cancel youtube premium', 'cancel youtube premium subscription'],
    related: ['spotify', 'apple-music', 'netflix'],
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    slug: 'how-to-cancel-amazon-prime',
    cancelUrl: 'https://www.amazon.com/mc/pipelines/cancelPrime',
    category: 'streaming',
    price: '$14.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel amazon prime', 'cancel amazon prime subscription', 'amazon prime cancellation'],
    related: ['netflix', 'hulu', 'max', 'audible'],
  },
  {
    id: 'max',
    name: 'Max (HBO)',
    slug: 'how-to-cancel-hbo-max',
    cancelUrl: 'https://www.max.com/account/subscription',
    category: 'streaming',
    price: '$15.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel hbo max', 'cancel max subscription', 'hbo max cancellation'],
    related: ['netflix', 'hulu', 'disney-plus', 'paramount-plus'],
  },
  {
    id: 'paramount-plus',
    name: 'Paramount+',
    slug: 'how-to-cancel-paramount-plus',
    cancelUrl: 'https://www.paramountplus.com/account/',
    category: 'streaming',
    price: '$11.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel paramount plus', 'cancel paramount+ subscription'],
    related: ['netflix', 'hulu', 'disney-plus', 'peacock'],
  },
  {
    id: 'peacock',
    name: 'Peacock',
    slug: 'how-to-cancel-peacock',
    cancelUrl: 'https://www.peacocktv.com/account/plan',
    category: 'streaming',
    price: '$11.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel peacock', 'cancel peacock subscription', 'peacock tv cancellation'],
    related: ['netflix', 'hulu', 'paramount-plus', 'max'],
  },
  {
    id: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud',
    slug: 'how-to-cancel-adobe-creative-cloud',
    cancelUrl: 'https://account.adobe.com/plans',
    category: 'productivity',
    price: '$54.99/mo',
    difficulty: 'hard',
    keywords: ['how to cancel adobe creative cloud', 'cancel adobe subscription', 'adobe cancellation fee'],
    related: ['canva', 'figma', 'midjourney'],
  },
  {
    id: 'chatgpt-plus',
    name: 'ChatGPT Plus',
    slug: 'how-to-cancel-chatgpt-plus',
    cancelUrl: 'https://chat.openai.com/settings/subscription',
    category: 'ai',
    price: '$20/mo',
    difficulty: 'easy',
    keywords: ['how to cancel chatgpt plus', 'cancel chatgpt subscription', 'chatgpt plus cancellation'],
    related: ['claude-pro', 'midjourney', 'perplexity', 'github-copilot'],
  },
  {
    id: 'claude-pro',
    name: 'Claude Pro',
    slug: 'how-to-cancel-claude-pro',
    cancelUrl: 'https://claude.ai/settings/billing',
    category: 'ai',
    price: '$20/mo',
    difficulty: 'easy',
    keywords: ['how to cancel claude pro', 'cancel claude subscription', 'anthropic claude cancellation'],
    related: ['chatgpt-plus', 'perplexity', 'midjourney'],
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    slug: 'how-to-cancel-midjourney',
    cancelUrl: 'https://www.midjourney.com/account/',
    category: 'ai',
    price: '$10/mo',
    difficulty: 'medium',
    keywords: ['how to cancel midjourney', 'cancel midjourney subscription', 'midjourney cancellation'],
    related: ['chatgpt-plus', 'claude-pro', 'adobe-creative-cloud'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity Pro',
    slug: 'how-to-cancel-perplexity',
    cancelUrl: 'https://www.perplexity.ai/settings/subscription',
    category: 'ai',
    price: '$20/mo',
    difficulty: 'easy',
    keywords: ['how to cancel perplexity', 'cancel perplexity pro', 'perplexity subscription cancel'],
    related: ['chatgpt-plus', 'claude-pro', 'github-copilot'],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    slug: 'how-to-cancel-github-copilot',
    cancelUrl: 'https://github.com/settings/billing/licensing',
    category: 'ai',
    price: 'varies',
    difficulty: 'easy',
    keywords: ['how to cancel github copilot', 'cancel copilot subscription'],
    related: ['chatgpt-plus', 'claude-pro', 'cursor'],
  },
  {
    id: 'cursor',
    name: 'Cursor Pro',
    slug: 'how-to-cancel-cursor',
    cancelUrl: 'https://cursor.com/dashboard',
    category: 'ai',
    price: '$20/mo',
    difficulty: 'easy',
    keywords: ['how to cancel cursor', 'cancel cursor pro subscription'],
    related: ['github-copilot', 'chatgpt-plus', 'claude-pro'],
  },
  {
    id: 'notion',
    name: 'Notion',
    slug: 'how-to-cancel-notion',
    cancelUrl: 'https://www.notion.so/my-account',
    category: 'productivity',
    price: '$10/mo',
    difficulty: 'easy',
    keywords: ['how to cancel notion', 'cancel notion subscription', 'notion plus cancellation'],
    related: ['slack', 'dropbox', 'evernote'],
  },
  {
    id: 'slack',
    name: 'Slack',
    slug: 'how-to-cancel-slack',
    cancelUrl: 'https://slack.com/intl/en-us/help/articles/218915077',
    category: 'productivity',
    price: '$8.75/mo',
    difficulty: 'medium',
    keywords: ['how to cancel slack', 'cancel slack subscription', 'slack pro cancellation'],
    related: ['notion', 'microsoft-365', 'dropbox'],
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    slug: 'how-to-cancel-dropbox',
    cancelUrl: 'https://www.dropbox.com/account/plan',
    category: 'productivity',
    price: '$11.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel dropbox', 'cancel dropbox subscription', 'dropbox plus cancellation'],
    related: ['notion', 'icloud', 'microsoft-365'],
  },
  {
    id: 'microsoft-365',
    name: 'Microsoft 365',
    slug: 'how-to-cancel-microsoft-365',
    cancelUrl: 'https://account.microsoft.com/services',
    category: 'productivity',
    price: '$9.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel microsoft 365', 'cancel office 365 subscription', 'microsoft 365 cancellation'],
    related: ['slack', 'dropbox', 'notion'],
  },
  {
    id: 'canva',
    name: 'Canva Pro',
    slug: 'how-to-cancel-canva-pro',
    cancelUrl: 'https://www.canva.com/settings/billing-and-plans',
    category: 'productivity',
    price: '$12.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel canva pro', 'cancel canva subscription', 'canva pro cancellation'],
    related: ['adobe-creative-cloud', 'figma', 'midjourney'],
  },
  {
    id: 'figma',
    name: 'Figma',
    slug: 'how-to-cancel-figma',
    cancelUrl: 'https://www.figma.com/settings',
    category: 'productivity',
    price: '$15/mo',
    difficulty: 'easy',
    keywords: ['how to cancel figma', 'cancel figma subscription', 'figma professional cancellation'],
    related: ['canva', 'adobe-creative-cloud', 'notion'],
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    slug: 'how-to-cancel-grammarly',
    cancelUrl: 'https://account.grammarly.com/subscription',
    category: 'productivity',
    price: '$12/mo',
    difficulty: 'medium',
    keywords: ['how to cancel grammarly', 'cancel grammarly premium', 'grammarly subscription cancel'],
    related: ['notion', 'chatgpt-plus', 'microsoft-365'],
  },
  {
    id: 'linkedin-premium',
    name: 'LinkedIn Premium',
    slug: 'how-to-cancel-linkedin-premium',
    cancelUrl: 'https://www.linkedin.com/mypreferences/d/manage-subscription',
    category: 'productivity',
    price: '$29.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel linkedin premium', 'cancel linkedin subscription'],
    related: ['microsoft-365', 'slack', 'grammarly'],
  },
  {
    id: 'evernote',
    name: 'Evernote',
    slug: 'how-to-cancel-evernote',
    cancelUrl: 'https://www.evernote.com/BillingInfo.action',
    category: 'productivity',
    price: '$14.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel evernote', 'cancel evernote subscription', 'evernote premium cancellation'],
    related: ['notion', 'dropbox', 'microsoft-365'],
  },
  {
    id: 'duolingo',
    name: 'Duolingo Plus',
    slug: 'how-to-cancel-duolingo',
    cancelUrl: 'https://www.duolingo.com/settings/account',
    category: 'lifestyle',
    price: '$6.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel duolingo', 'cancel duolingo plus', 'duolingo super cancellation'],
    related: ['headspace', 'calm', 'medium'],
  },
  {
    id: 'headspace',
    name: 'Headspace',
    slug: 'how-to-cancel-headspace',
    cancelUrl: 'https://www.headspace.com/subscription/manage',
    category: 'lifestyle',
    price: '$12.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel headspace', 'cancel headspace subscription', 'headspace cancellation'],
    related: ['calm', 'duolingo', 'nytimes'],
  },
  {
    id: 'calm',
    name: 'Calm',
    slug: 'how-to-cancel-calm',
    cancelUrl: 'https://www.calm.com/account/subscription',
    category: 'lifestyle',
    price: '$14.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel calm', 'cancel calm subscription', 'calm app cancellation'],
    related: ['headspace', 'duolingo', 'nytimes'],
  },
  {
    id: 'tinder',
    name: 'Tinder',
    slug: 'how-to-cancel-tinder',
    cancelUrl: 'https://tinder.com/app/settings',
    category: 'lifestyle',
    price: '$14.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel tinder', 'cancel tinder gold', 'tinder plus cancellation'],
    related: ['bumble', 'headspace', 'calm'],
  },
  {
    id: 'bumble',
    name: 'Bumble',
    slug: 'how-to-cancel-bumble',
    cancelUrl: 'https://bumble.com/en/help/how-do-i-cancel-my-subscription',
    category: 'lifestyle',
    price: '$16.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel bumble', 'cancel bumble premium', 'bumble subscription cancel'],
    related: ['tinder', 'headspace', 'calm'],
  },
  {
    id: 'nytimes',
    name: 'New York Times',
    slug: 'how-to-cancel-new-york-times',
    cancelUrl: 'https://myaccount.nytimes.com/seg/',
    category: 'media',
    price: '$17/mo',
    difficulty: 'hard',
    keywords: ['how to cancel new york times', 'cancel nyt subscription', 'nytimes cancellation'],
    related: ['medium', 'the-athletic', 'substack'],
  },
  {
    id: 'medium',
    name: 'Medium',
    slug: 'how-to-cancel-medium',
    cancelUrl: 'https://medium.com/me/settings/membership',
    category: 'media',
    price: '$5/mo',
    difficulty: 'easy',
    keywords: ['how to cancel medium', 'cancel medium membership', 'medium subscription cancel'],
    related: ['substack', 'nytimes', 'the-athletic'],
  },
  {
    id: 'the-athletic',
    name: 'The Athletic',
    slug: 'how-to-cancel-the-athletic',
    cancelUrl: 'https://www.nytimes.com/athletic/settings',
    category: 'media',
    price: 'varies',
    difficulty: 'medium',
    keywords: ['how to cancel the athletic', 'cancel athletic subscription'],
    related: ['nytimes', 'medium', 'substack'],
  },
  {
    id: 'substack',
    name: 'Substack',
    slug: 'how-to-cancel-substack',
    cancelUrl: 'https://substack.com/account/payments',
    category: 'media',
    price: 'varies',
    difficulty: 'easy',
    keywords: ['how to cancel substack', 'cancel substack subscription', 'unsubscribe substack'],
    related: ['medium', 'nytimes', 'the-athletic'],
  },
  {
    id: 'nordvpn',
    name: 'NordVPN',
    slug: 'how-to-cancel-nordvpn',
    cancelUrl: 'https://my.nordaccount.com/dashboard/nordvpn/',
    category: 'vpn',
    price: 'varies',
    difficulty: 'medium',
    keywords: ['how to cancel nordvpn', 'cancel nordvpn subscription', 'nordvpn cancellation refund'],
    related: ['expressvpn', '1password', 'lastpass'],
  },
  {
    id: 'expressvpn',
    name: 'ExpressVPN',
    slug: 'how-to-cancel-expressvpn',
    cancelUrl: 'https://www.expressvpn.com/subscriptions',
    category: 'vpn',
    price: '$12.95/mo',
    difficulty: 'medium',
    keywords: ['how to cancel expressvpn', 'cancel expressvpn subscription', 'expressvpn cancellation'],
    related: ['nordvpn', '1password', 'lastpass'],
  },
  {
    id: '1password',
    name: '1Password',
    slug: 'how-to-cancel-1password',
    cancelUrl: 'https://my.1password.com/settings/billing',
    category: 'productivity',
    price: '$2.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel 1password', 'cancel 1password subscription'],
    related: ['lastpass', 'nordvpn', 'expressvpn'],
  },
  {
    id: 'lastpass',
    name: 'LastPass',
    slug: 'how-to-cancel-lastpass',
    cancelUrl: 'https://lastpass.com/billing_update.php',
    category: 'productivity',
    price: '$3/mo',
    difficulty: 'medium',
    keywords: ['how to cancel lastpass', 'cancel lastpass premium', 'lastpass subscription cancel'],
    related: ['1password', 'nordvpn', 'expressvpn'],
  },
  {
    id: 'audible',
    name: 'Audible',
    slug: 'how-to-cancel-audible',
    cancelUrl: 'https://www.audible.com/account/cancel-membership',
    category: 'media',
    price: '$14.95/mo',
    difficulty: 'hard',
    keywords: ['how to cancel audible', 'cancel audible subscription', 'audible membership cancellation'],
    related: ['amazon-prime', 'kindle-unlimited', 'spotify'],
  },
  {
    id: 'kindle-unlimited',
    name: 'Kindle Unlimited',
    slug: 'how-to-cancel-kindle-unlimited',
    cancelUrl: 'https://www.amazon.com/kindle-dbs/ku/options',
    category: 'media',
    price: '$11.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel kindle unlimited', 'cancel kindle unlimited subscription'],
    related: ['audible', 'amazon-prime', 'medium'],
  },
  {
    id: 'xbox-game-pass',
    name: 'Xbox Game Pass',
    slug: 'how-to-cancel-xbox-game-pass',
    cancelUrl: 'https://account.microsoft.com/services',
    category: 'gaming',
    price: '$14.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel xbox game pass', 'cancel game pass subscription', 'xbox game pass cancellation'],
    related: ['playstation-plus', 'nintendo-switch-online', 'microsoft-365'],
  },
  {
    id: 'playstation-plus',
    name: 'PlayStation Plus',
    slug: 'how-to-cancel-playstation-plus',
    cancelUrl: 'https://www.playstation.com/en-us/support/subscriptions/cancel-playstation-plus/',
    category: 'gaming',
    price: 'varies',
    difficulty: 'medium',
    keywords: ['how to cancel playstation plus', 'cancel ps plus subscription', 'ps plus cancellation'],
    related: ['xbox-game-pass', 'nintendo-switch-online', 'crunchyroll'],
  },
  {
    id: 'nintendo-switch-online',
    name: 'Nintendo Switch Online',
    slug: 'how-to-cancel-nintendo-switch-online',
    cancelUrl: 'https://accounts.nintendo.com/portal',
    category: 'gaming',
    price: 'varies',
    difficulty: 'medium',
    keywords: ['how to cancel nintendo switch online', 'cancel switch online subscription'],
    related: ['xbox-game-pass', 'playstation-plus', 'crunchyroll'],
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    slug: 'how-to-cancel-crunchyroll',
    cancelUrl: 'https://www.crunchyroll.com/account/subscription',
    category: 'streaming',
    price: '$7.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel crunchyroll', 'cancel crunchyroll subscription', 'crunchyroll premium cancel'],
    related: ['netflix', 'hulu', 'disney-plus'],
  },
  {
    id: 'icloud',
    name: 'iCloud+',
    slug: 'how-to-cancel-icloud',
    cancelUrl: 'https://support.apple.com/en-us/HT207594',
    category: 'productivity',
    price: '$2.99/mo',
    difficulty: 'medium',
    keywords: ['how to cancel icloud', 'cancel icloud storage subscription', 'icloud+ cancellation'],
    related: ['dropbox', 'apple-music', 'apple-tv-plus'],
  },
  {
    id: 'fubotv',
    name: 'FuboTV',
    slug: 'how-to-cancel-fubotv',
    cancelUrl: 'https://my.fubo.tv/settings/subscription',
    category: 'streaming',
    price: '$79.99/mo',
    difficulty: 'hard',
    keywords: ['how to cancel fubotv', 'cancel fubo free trial', 'fubo subscription cancel', 'fubotv cancel'],
    related: ['youtube-premium', 'hulu', 'netflix'],
  },
  {
    id: 'youtube-tv',
    name: 'YouTube TV',
    slug: 'how-to-cancel-youtube-tv',
    cancelUrl: 'https://tv.youtube.com/settings/membership',
    category: 'streaming',
    price: '$72.99/mo',
    difficulty: 'easy',
    keywords: ['how to cancel youtube tv', 'cancel youtube tv subscription', 'youtube tv refund'],
    related: ['fubotv', 'hulu', 'netflix'],
  },
];

export const CATEGORIES = {
  streaming: { label: 'Streaming & Entertainment', icon: '📺' },
  ai: { label: 'AI & Machine Learning', icon: '🤖' },
  productivity: { label: 'Productivity & Tools', icon: '⚡' },
  lifestyle: { label: 'Lifestyle & Wellness', icon: '🧘' },
  media: { label: 'News & Reading', icon: '📰' },
  gaming: { label: 'Gaming', icon: '🎮' },
  vpn: { label: 'VPN & Security', icon: '🔒' },
};

export function getServiceById(id) {
  return SERVICES.find(s => s.id === id);
}

export function getRelatedServices(service) {
  return service.related
    .map(id => SERVICES.find(s => s.id === id))
    .filter(Boolean);
}

export function getServicesByCategory(category) {
  return SERVICES.filter(s => s.category === category);
}
