const CANCEL_LINKS = {
  'netflix': 'https://www.netflix.com/cancelplan',
  'spotify': 'https://www.spotify.com/account/subscription/',
  'hulu': 'https://secure.hulu.com/account',
  'disney+': 'https://www.disneyplus.com/account/subscription',
  'disney plus': 'https://www.disneyplus.com/account/subscription',
  'apple music': 'https://support.apple.com/en-us/HT202039',
  'apple tv+': 'https://support.apple.com/en-us/HT202039',
  'apple tv': 'https://support.apple.com/en-us/HT202039',
  'apple one': 'https://support.apple.com/en-us/HT211659',
  'icloud': 'https://support.apple.com/en-us/HT207594',
  'youtube premium': 'https://www.youtube.com/paid_memberships',
  'youtube music': 'https://www.youtube.com/paid_memberships',
  'amazon prime': 'https://www.amazon.com/mc/pipelines/cancelPrime',
  'prime video': 'https://www.amazon.com/mc/pipelines/cancelPrime',
  'hbo max': 'https://www.max.com/account/subscription',
  'max': 'https://www.max.com/account/subscription',
  'paramount+': 'https://www.paramountplus.com/account/',
  'paramount plus': 'https://www.paramountplus.com/account/',
  'peacock': 'https://www.peacocktv.com/account/plan',
  'adobe': 'https://account.adobe.com/plans',
  'adobe creative cloud': 'https://account.adobe.com/plans',
  'chatgpt': 'https://chat.openai.com/settings/subscription',
  'chatgpt plus': 'https://chat.openai.com/settings/subscription',
  'openai': 'https://chat.openai.com/settings/subscription',
  'notion': 'https://www.notion.so/my-account',
  'slack': 'https://slack.com/intl/en-us/help/articles/218915077',
  'dropbox': 'https://www.dropbox.com/account/plan',
  'microsoft 365': 'https://account.microsoft.com/services',
  'office 365': 'https://account.microsoft.com/services',
  'xbox game pass': 'https://account.microsoft.com/services',
  'playstation plus': 'https://store.playstation.com/subscriptions',
  'ps plus': 'https://store.playstation.com/subscriptions',
  'nintendo switch online': 'https://ec.nintendo.com/my/membership',
  'canva': 'https://www.canva.com/settings/billing-and-plans',
  'figma': 'https://www.figma.com/settings',
  'grammarly': 'https://account.grammarly.com/subscription',
  'medium': 'https://medium.com/me/settings/membership',
  'substack': 'https://substack.com/account/payments',
  'linkedin premium': 'https://www.linkedin.com/mypreferences/d/manage-subscription',
  'tinder': 'https://tinder.com/app/settings',
  'bumble': 'https://bumble.com/en/help/how-do-i-cancel-my-subscription',
  'headspace': 'https://www.headspace.com/settings/subscription',
  'calm': 'https://www.calm.com/account/subscription',
  'nytimes': 'https://myaccount.nytimes.com/seg/',
  'new york times': 'https://myaccount.nytimes.com/seg/',
  'the athletic': 'https://theathletic.com/account',
  'duolingo': 'https://www.duolingo.com/settings/account',
  'evernote': 'https://www.evernote.com/BillingInfo.action',
  '1password': 'https://my.1password.com/settings/billing',
  'lastpass': 'https://lastpass.com/billing_update.php',
  'nordvpn': 'https://my.nordaccount.com/dashboard/nordvpn/',
  'expressvpn': 'https://www.expressvpn.com/subscriptions',
  'audible': 'https://www.audible.com/account/cancel-membership',
  'kindle unlimited': 'https://www.amazon.com/kindle-dbs/ku/options',
  'crunchyroll': 'https://www.crunchyroll.com/account/subscription',
  'cursor': 'https://www.cursor.com/settings',
  'github copilot': 'https://github.com/settings/copilot',
  'copilot': 'https://github.com/settings/copilot',
  'claude': 'https://claude.ai/settings/billing',
  'anthropic': 'https://claude.ai/settings/billing',
  'midjourney': 'https://www.midjourney.com/account/',
  'dalle': 'https://chat.openai.com/settings/subscription',
  'perplexity': 'https://www.perplexity.ai/settings/subscription',
};

export function getCancelLink(subscriptionName) {
  if (!subscriptionName) return null;
  const key = subscriptionName.toLowerCase().trim();
  if (CANCEL_LINKS[key]) return CANCEL_LINKS[key];
  for (const [k, v] of Object.entries(CANCEL_LINKS)) {
    if (key.includes(k) || k.includes(key)) return v;
  }
  return null;
}
